name: CI/CD
on: [push, pull_request]
jobs:
  ci:
    name: Run Tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: sad-path (retry_wait_seconds)
        id: sad_path_wait_sec
        uses: nick-invision/retry@v2
        continue-on-error: true
        with:
          timeout_minutes: 1
          max_attempts: 3
          retry_wait_seconds: 15
          command: npm install this-isnt-a-real-package-name-zzz
